### ISSUE TITLE
Zürich Area Groups in Bioinformatics, Data Science and Computational Biology. get an error.

### ISSUE THREAD

**Issue by avivleemann** [compbiozurich/compbiozurich.github.io#16]
when i try to look at  Zürich Area Groups in Bioinformatics, Data Science and Computational Biology.
i get this error :
 
{
  "error": {
    "errorCode": 422,
    "errorMessage": "No query generated - missing or malformed parameters"
  },
  "meta": {
    "apiVersion": "v2.1.0-beaconplus",
    "beaconId": "org.progenetix",
    "receivedRequestSummary": {
      "apiVersion": "v2.1.0-beaconplus",
      "beaconId": "org.progenetix",
      "datasetIds": [
        "progenetix"
      ],
      "filters": [],
      "includeResultsetResponses": "HIT",
      "pagination": {
        "limit": 200,
        "skip": 0
      },
      "requestParameters": {
        "$schema": null
      },
      "requestedGranularity": "record",
      "requestedSchemas": [
        {
          "entityType": "GeoLocation",
          "schema": "https://progenetix.org/services/schemas/GeoLocation/"
        }
      ],
      "testMode": false
    },
    "returnedGranularity": "record",
    "returnedSchemas": [
      {
        "entityType": "GeoLocation",
        "schema": "https://progenetix.org/services/schemas/GeoLocation/"
      }
    ],
    "testMode": false,
    "warnings": [
      "!!! Unmatched parameter file: https://raw.githubusercontent.com/compbiozurich/compbiozurich.github.io/main/collab/people.tab",
      "!!! Unmatched parameter marker_type: marker",
      "!!! Unmatched parameter map_h_px: 480",
      "!!! Unmatched parameter map_w_px: 600"
    ]
  }
![Zürich Area Groups in Bioinformatics, Data Science and Computational Biology - CompbioZurich ](https://github.com/user-attachments/assets/6056abb8-1057-42ff-96a2-97b9f0ba1928)

**Comment by mbaudis** [comment]
Thanks for the note; probably had been there for a while. Fixed with a temporary hack to static picture (https://github.com/compbiozurich/compbiozurich.github.io/commit/e5b49ebcfce3613f045a995f140fb1d389f921b2); I'll update the dynamic links at some point ...


Btw. what you see is a Beacon-style error message with custom warnings from our server `¯\_(ツ)_/¯`

**Comment by mbaudis** [comment]
... closing this as temporarily fixed.
